//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 6/17/2018 12:05:06 PM
namespace checkout.com.client.Checkout.Com.Api.Entities
{
    /// <summary>
    /// There are no comments for ProductSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ProductSingle")]
    public partial class ProductSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Product>
    {
        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Product> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Product")]
    public partial class Product : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        public static Product CreateProduct(string ID)
        {
            Product product = new Product();
            product.Id = ID;
            return product;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Brand in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Brand")]
        public string Brand
        {
            get
            {
                return this._Brand;
            }
            set
            {
                this.OnBrandChanging(value);
                this._Brand = value;
                this.OnBrandChanged();
                this.OnPropertyChanged("Brand");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private string _Brand;
        partial void OnBrandChanging(string value);
        partial void OnBrandChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Price")]
        public global::System.Nullable<decimal> Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
                this.OnPropertyChanged("Price");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private global::System.Nullable<decimal> _Price;
        partial void OnPriceChanging(global::System.Nullable<decimal> value);
        partial void OnPriceChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ItemSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ItemSingle")]
    public partial class ItemSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Item>
    {
        /// <summary>
        /// Initialize a new ItemSingle object.
        /// </summary>
        public ItemSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ItemSingle object.
        /// </summary>
        public ItemSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ItemSingle object.
        /// </summary>
        public ItemSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Item> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Order")]
        public global::checkout.com.client.Checkout.Com.Api.Entities.OrderSingle Order
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Order == null))
                {
                    this._Order = new global::checkout.com.client.Checkout.Com.Api.Entities.OrderSingle(this.Context, GetPath("Order"));
                }
                return this._Order;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private global::checkout.com.client.Checkout.Com.Api.Entities.OrderSingle _Order;
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Product")]
        public global::checkout.com.client.Checkout.Com.Api.Entities.ProductSingle Product
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Product == null))
                {
                    this._Product = new global::checkout.com.client.Checkout.Com.Api.Entities.ProductSingle(this.Context, GetPath("Product"));
                }
                return this._Product;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private global::checkout.com.client.Checkout.Com.Api.Entities.ProductSingle _Product;
    }
    /// <summary>
    /// There are no comments for Item in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Item")]
    public partial class Item : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="quantity">Initial value of Quantity.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        public static Item CreateItem(string ID, int quantity)
        {
            Item item = new Item();
            item.Id = ID;
            item.Quantity = quantity;
            return item;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property OrderId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("OrderId")]
        public string OrderId
        {
            get
            {
                return this._OrderId;
            }
            set
            {
                this.OnOrderIdChanging(value);
                this._OrderId = value;
                this.OnOrderIdChanged();
                this.OnPropertyChanged("OrderId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private string _OrderId;
        partial void OnOrderIdChanging(string value);
        partial void OnOrderIdChanged();
        /// <summary>
        /// There are no comments for Property ProductId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProductId")]
        public string ProductId
        {
            get
            {
                return this._ProductId;
            }
            set
            {
                this.OnProductIdChanging(value);
                this._ProductId = value;
                this.OnProductIdChanged();
                this.OnPropertyChanged("ProductId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private string _ProductId;
        partial void OnProductIdChanging(string value);
        partial void OnProductIdChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Quantity")]
        public int Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this._Quantity = value;
                this.OnQuantityChanged();
                this.OnPropertyChanged("Quantity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private int _Quantity;
        partial void OnQuantityChanging(int value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Order")]
        public global::checkout.com.client.Checkout.Com.Api.Entities.Order Order
        {
            get
            {
                return this._Order;
            }
            set
            {
                this.OnOrderChanging(value);
                this._Order = value;
                this.OnOrderChanged();
                this.OnPropertyChanged("Order");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private global::checkout.com.client.Checkout.Com.Api.Entities.Order _Order;
        partial void OnOrderChanging(global::checkout.com.client.Checkout.Com.Api.Entities.Order value);
        partial void OnOrderChanged();
        /// <summary>
        /// There are no comments for Property Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Product")]
        public global::checkout.com.client.Checkout.Com.Api.Entities.Product Product
        {
            get
            {
                return this._Product;
            }
            set
            {
                this.OnProductChanging(value);
                this._Product = value;
                this.OnProductChanged();
                this.OnPropertyChanged("Product");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private global::checkout.com.client.Checkout.Com.Api.Entities.Product _Product;
        partial void OnProductChanging(global::checkout.com.client.Checkout.Com.Api.Entities.Product value);
        partial void OnProductChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OrderSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("OrderSingle")]
    public partial class OrderSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Order>
    {
        /// <summary>
        /// Initialize a new OrderSingle object.
        /// </summary>
        public OrderSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new OrderSingle object.
        /// </summary>
        public OrderSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new OrderSingle object.
        /// </summary>
        public OrderSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Order> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Items in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Items")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Item> Items
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Items == null))
                {
                    this._Items = Context.CreateQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Item>(GetPath("Items"));
                }
                return this._Items;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Item> _Items;
    }
    /// <summary>
    /// There are no comments for Order in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Order")]
    public partial class Order : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        public static Order CreateOrder(string ID)
        {
            Order order = new Order();
            order.Id = ID;
            return order;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CustomerName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CustomerName")]
        public string CustomerName
        {
            get
            {
                return this._CustomerName;
            }
            set
            {
                this.OnCustomerNameChanging(value);
                this._CustomerName = value;
                this.OnCustomerNameChanged();
                this.OnPropertyChanged("CustomerName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private string _CustomerName;
        partial void OnCustomerNameChanging(string value);
        partial void OnCustomerNameChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedDate")]
        public global::System.Nullable<global::System.DateTimeOffset> CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this._CreatedDate = value;
                this.OnCreatedDateChanged();
                this.OnPropertyChanged("CreatedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedDate;
        partial void OnCreatedDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property Items in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Items")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::checkout.com.client.Checkout.Com.Api.Entities.Item> Items
        {
            get
            {
                return this._Items;
            }
            set
            {
                this.OnItemsChanging(value);
                this._Items = value;
                this.OnItemsChanged();
                this.OnPropertyChanged("Items");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::checkout.com.client.Checkout.Com.Api.Entities.Item> _Items = new global::Microsoft.OData.Client.DataServiceCollection<global::checkout.com.client.Checkout.Com.Api.Entities.Item>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnItemsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::checkout.com.client.Checkout.Com.Api.Entities.Item> value);
        partial void OnItemsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::checkout.com.client.Checkout.Com.Api.Entities.Product as global::checkout.com.client.Checkout.Com.Api.Entities.ProductSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::checkout.com.client.Checkout.Com.Api.Entities.ProductSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Product> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::checkout.com.client.Checkout.Com.Api.Entities.ProductSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::checkout.com.client.Checkout.Com.Api.Entities.Product as global::checkout.com.client.Checkout.Com.Api.Entities.ProductSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::checkout.com.client.Checkout.Com.Api.Entities.ProductSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Product> source,
            string id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::checkout.com.client.Checkout.Com.Api.Entities.ProductSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::checkout.com.client.Checkout.Com.Api.Entities.Item as global::checkout.com.client.Checkout.Com.Api.Entities.ItemSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::checkout.com.client.Checkout.Com.Api.Entities.ItemSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Item> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::checkout.com.client.Checkout.Com.Api.Entities.ItemSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::checkout.com.client.Checkout.Com.Api.Entities.Item as global::checkout.com.client.Checkout.Com.Api.Entities.ItemSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::checkout.com.client.Checkout.Com.Api.Entities.ItemSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Item> source,
            string id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::checkout.com.client.Checkout.Com.Api.Entities.ItemSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::checkout.com.client.Checkout.Com.Api.Entities.Order as global::checkout.com.client.Checkout.Com.Api.Entities.OrderSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::checkout.com.client.Checkout.Com.Api.Entities.OrderSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Order> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::checkout.com.client.Checkout.Com.Api.Entities.OrderSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::checkout.com.client.Checkout.Com.Api.Entities.Order as global::checkout.com.client.Checkout.Com.Api.Entities.OrderSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::checkout.com.client.Checkout.Com.Api.Entities.OrderSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Order> source,
            string id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::checkout.com.client.Checkout.Com.Api.Entities.OrderSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace checkout.com.client.Checkout.Com.Api.Dto
{
    /// <summary>
    /// There are no comments for Billing in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Billing")]
    public partial class Billing : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property CreditCardNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreditCardNumber")]
        public string CreditCardNumber
        {
            get
            {
                return this._CreditCardNumber;
            }
            set
            {
                this.OnCreditCardNumberChanging(value);
                this._CreditCardNumber = value;
                this.OnCreditCardNumberChanged();
                this.OnPropertyChanged("CreditCardNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private string _CreditCardNumber;
        partial void OnCreditCardNumberChanging(string value);
        partial void OnCreditCardNumberChanged();
        /// <summary>
        /// There are no comments for Property CCV in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CCV")]
        public string CCV
        {
            get
            {
                return this._CCV;
            }
            set
            {
                this.OnCCVChanging(value);
                this._CCV = value;
                this.OnCCVChanged();
                this.OnPropertyChanged("CCV");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private string _CCV;
        partial void OnCCVChanging(string value);
        partial void OnCCVChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
namespace checkout.com.client.Checkout
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "checkout.com.api.Entities", "checkout.com.client.Checkout.Com.Api.Entities");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "checkout.com.api.Dto", "checkout.com.client.Checkout.Com.Api.Dto");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Checkout", "checkout.com.client.Checkout");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("checkout.com.client.Checkout.Com.Api.Entities", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("checkout.com.api.Entities.", originalNameAttribute.OriginalName);
                }
                return string.Concat("checkout.com.api.Entities.", clientType.Name);
            }
            if (clientType.Namespace.Equals("checkout.com.client.Checkout.Com.Api.Dto", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("checkout.com.api.Dto.", originalNameAttribute.OriginalName);
                }
                return string.Concat("checkout.com.api.Dto.", clientType.Name);
            }
            if (clientType.Namespace.Equals("checkout.com.client.Checkout", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Checkout.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Checkout.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Product")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Product> Product
        {
            get
            {
                if ((this._Product == null))
                {
                    this._Product = base.CreateQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Product>("Product");
                }
                return this._Product;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Product> _Product;
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Item")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Item> Item
        {
            get
            {
                if ((this._Item == null))
                {
                    this._Item = base.CreateQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Item>("Item");
                }
                return this._Item;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Item> _Item;
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Order")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Order> Order
        {
            get
            {
                if ((this._Order == null))
                {
                    this._Order = base.CreateQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Order>("Order");
                }
                return this._Order;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::checkout.com.client.Checkout.Com.Api.Entities.Order> _Order;
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        public void AddToProduct(global::checkout.com.client.Checkout.Com.Api.Entities.Product product)
        {
            base.AddObject("Product", product);
        }
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        public void AddToItem(global::checkout.com.client.Checkout.Com.Api.Entities.Item item)
        {
            base.AddObject("Item", item);
        }
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        public void AddToOrder(global::checkout.com.client.Checkout.Com.Api.Entities.Order order)
        {
            base.AddObject("Order", order);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""checkout.com.api.Entities"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Product"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" MaxLength=""50"" />
        <Property Name=""Brand"" Type=""Edm.String"" MaxLength=""30"" />
        <Property Name=""Price"" Type=""Edm.Decimal"" />
      </EntityType>
      <EntityType Name=""Item"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""OrderId"" Type=""Edm.String"" />
        <Property Name=""ProductId"" Type=""Edm.String"" />
        <Property Name=""Quantity"" Type=""Edm.Int32"" Nullable=""false"" />
        <NavigationProperty Name=""Order"" Type=""checkout.com.api.Entities.Order"">
          <ReferentialConstraint Property=""OrderId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
        <NavigationProperty Name=""Product"" Type=""checkout.com.api.Entities.Product"">
          <ReferentialConstraint Property=""ProductId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
      </EntityType>
      <EntityType Name=""Order"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""CustomerName"" Type=""Edm.String"" MaxLength=""50"" />
        <Property Name=""CreatedDate"" Type=""Edm.DateTimeOffset"" />
        <NavigationProperty Name=""Items"" Type=""Collection(checkout.com.api.Entities.Item)"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""checkout.com.api.Dto"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <ComplexType Name=""Billing"">
        <Property Name=""CreditCardNumber"" Type=""Edm.String"" />
        <Property Name=""CCV"" Type=""Edm.String"" />
      </ComplexType>
    </Schema>
    <Schema Namespace=""Checkout"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <Action Name=""Process"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""checkout.com.api.Entities.Order"" />
        <Parameter Name=""Billing"" Type=""checkout.com.api.Dto.Billing"" />
      </Action>
      <Action Name=""AddItems"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""checkout.com.api.Entities.Order"" />
        <Parameter Name=""Items"" Type=""Collection(checkout.com.api.Entities.Item)"" />
      </Action>
      <Action Name=""RemoveItems"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""checkout.com.api.Entities.Order"" />
        <Parameter Name=""Items"" Type=""Collection(checkout.com.api.Entities.Item)"" />
      </Action>
      <Action Name=""Clear"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""checkout.com.api.Entities.Order"" />
        <Parameter Name=""Delete"" Type=""Edm.Boolean"" Nullable=""false"" />
      </Action>
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Product"" EntityType=""checkout.com.api.Entities.Product"" />
        <EntitySet Name=""Item"" EntityType=""checkout.com.api.Entities.Item"">
          <NavigationPropertyBinding Path=""Order"" Target=""Order"" />
          <NavigationPropertyBinding Path=""Product"" Target=""Product"" />
        </EntitySet>
        <EntitySet Name=""Order"" EntityType=""checkout.com.api.Entities.Order"">
          <NavigationPropertyBinding Path=""Items"" Target=""Item"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.CsdlReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.4.4")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// There are no comments for Process in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("Process")]
        public static global::Microsoft.OData.Client.DataServiceActionQuery Process(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::checkout.com.client.Checkout.Com.Api.Entities.Order> source, global::checkout.com.client.Checkout.Com.Api.Dto.Billing Billing)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuery(source.Context, source.AppendRequestUri("Checkout.Process"), new global::Microsoft.OData.Client.BodyOperationParameter("Billing", Billing));
        }
        /// <summary>
        /// There are no comments for AddItems in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("AddItems")]
        public static global::Microsoft.OData.Client.DataServiceActionQuery AddItems(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::checkout.com.client.Checkout.Com.Api.Entities.Order> source, global::System.Collections.Generic.ICollection<global::checkout.com.client.Checkout.Com.Api.Entities.Item> Items)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuery(source.Context, source.AppendRequestUri("Checkout.AddItems"), new global::Microsoft.OData.Client.BodyOperationParameter("Items", Items));
        }
        /// <summary>
        /// There are no comments for RemoveItems in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("RemoveItems")]
        public static global::Microsoft.OData.Client.DataServiceActionQuery RemoveItems(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::checkout.com.client.Checkout.Com.Api.Entities.Order> source, global::System.Collections.Generic.ICollection<global::checkout.com.client.Checkout.Com.Api.Entities.Item> Items)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuery(source.Context, source.AppendRequestUri("Checkout.RemoveItems"), new global::Microsoft.OData.Client.BodyOperationParameter("Items", Items));
        }
        /// <summary>
        /// There are no comments for Clear in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("Clear")]
        public static global::Microsoft.OData.Client.DataServiceActionQuery Clear(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::checkout.com.client.Checkout.Com.Api.Entities.Order> source, bool Delete)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuery(source.Context, source.AppendRequestUri("Checkout.Clear"), new global::Microsoft.OData.Client.BodyOperationParameter("Delete", Delete));
        }
    }
}
